/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/x1KnphdI7BB
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { IBM_Plex_Sans } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

ibm_plex_sans({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client";

import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { BoltIcon, BugIcon, FlameIcon, GlassWaterIcon, LeafIcon } from "./icon";

export function Header() {
  return (
    <div>
      <header className="bg-primary text-primary-foreground py-4 px-6">
        <nav className="flex items-center justify-between">
          <div className="flex items-center gap-4">
            <Link href="/" className="text-xl font-bold" prefetch={false}>
              Pokédex
            </Link>
            <nav></nav>
            <div className="flex items-center gap-2">
              {/* Fire */}
              <Button variant="ghost" size="sm">
                <FlameIcon className="w-5 h-5" />
                <Link href="/type/fire" className="px-2 py-1 mx-1 text-sm">
                  Fire
                </Link>
              </Button>

              {/* Water */}
              <Button variant="ghost" size="sm">
                <GlassWaterIcon className="w-5 h-5" />
                <Link href="/type/water" className="px-2 py-1 mx-1 text-sm">
                  Water
                </Link>
              </Button>

              {/* Grass */}
              <Button variant="ghost" size="sm">
                <LeafIcon className="w-5 h-5" />
                <Link href="/type/grass" className="px-2 py-1 mx-1 text-sm">
                  Grass
                </Link>
              </Button>
              {/* Electric */}
              <Button variant="ghost" size="sm">
                <BoltIcon className="w-5 h-5" />
                <Link href="/type/electric" className="px-2 py-1 mx-1 text-sm">
                  Electric
                </Link>
              </Button>

              {/* Bug */}
              <Button variant="ghost" size="sm">
                <BugIcon className="w-5 h-5" />
                <Link href="/type/bug" className="px-2 py-1 mx-1 text-sm">
                  Bug
                </Link>
              </Button>
            </div>
          </div>
          {/* 検索バー */}
          <div className="flex">
            <Input
              placeholder="Search Pokémon..."
              className="bg-primary-foreground/10 text-primary-foreground placeholder:text-primary-foreground/50 px-3 py-2 rounded-lg w-64"
            />
          </div>
        </nav>
      </header>
    </div>
  );
}
