/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/x1KnphdI7BB
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { IBM_Plex_Sans } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

ibm_plex_sans({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client";

import Link from "next/link";
import { useEffect, useState } from "react";

interface PokemonData {
  name: string;
  types: { type: { name: string } }[];
  height: number;
  weight: number;
  abilities: { ability: { name: string } }[];
  base_experience: number;
  sprites: {
    front_default: string;
  };
}

export function Pokemon() {
  const [pokemonList, setPokemonList] = useState<PokemonData[]>([]);

  useEffect(() => {
    const fetchPokemon = async () => {
      try {
        const response = await fetch(
          "https://pokeapi.co/api/v2/pokemon?limit=20"
        );
        const data = await response.json();
        const results = await Promise.all(
          data.results.map(async (pokemon: { url: string }) => {
            const res = await fetch(pokemon.url);
            return res.json();
          })
        );
        setPokemonList(results);
      } catch (error) {
        console.error("ポケモンデータの取得に失敗しました:", error);
      }
    };

    fetchPokemon();
  }, []);

  return (
    <div className="flex flex-col h-screen">
      <main className="flex-1 bg-muted/10 py-8">
        <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6 px-6">
          {pokemonList.map((pokemon) => (
            <Link href={`/pokemon/${pokemon.name}`} key={pokemon.name}>
              <div className="bg-background rounded-lg shadow-lg overflow-hidden cursor-pointer">
                <div
                  key={pokemon.name}
                  className="bg-background rounded-lg shadow-lg overflow-hidden"
                >
                  <img
                    src={pokemon.sprites.front_default}
                    alt={pokemon.name}
                    width={300}
                    height={300}
                    className="w-full h-48 object-cover"
                    style={{ aspectRatio: "300/300", objectFit: "cover" }}
                  />
                  <div className="p-4">
                    <h3 className="text-xl font-bold">{pokemon.name}</h3>
                    <div className="flex items-center gap-2 mt-2">
                      {pokemon.types.map((type) => (
                        <div
                          key={type.type.name}
                          className="bg-primary rounded-full px-3 py-1 text-primary-foreground text-sm font-medium"
                        >
                          {type.type.name}
                        </div>
                      ))}
                    </div>
                    <div className="mt-4 grid grid-cols-2 gap-2">
                      <div className="bg-muted/20 rounded-lg px-3 py-2 text-sm">
                        <div className="font-medium">Height</div>
                        <div>{pokemon.height / 10} m</div>
                      </div>
                      <div className="bg-muted/20 rounded-lg px-3 py-2 text-sm">
                        <div className="font-medium">Weight</div>
                        <div>{pokemon.weight / 10} kg</div>
                      </div>
                      <div className="bg-muted/20 rounded-lg px-3 py-2 text-sm">
                        <div className="font-medium">Abilities</div>
                        <div>
                          {pokemon.abilities
                            .map((a) => a.ability.name)
                            .join(", ")}
                        </div>
                      </div>
                      <div className="bg-muted/20 rounded-lg px-3 py-2 text-sm">
                        <div className="font-medium">Base Exp.</div>
                        <div>{pokemon.base_experience}</div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </Link>
          ))}
        </div>
      </main>
    </div>
  );
}